CC=g++

OPENGLLIB= -lGL
GLEWLIB= -lGLEW
GLFWLIB = -lglfw
LIBS=$(OPENGLLIB) $(GLEWLIB) $(GLFWLIB)
LDFLAGS=-L/usr/local/lib 
CPPFLAGS=-I/usr/local/include -I./

BIN=bike_model
SRCS=bike_model.cpp gl_framework.cpp shader_util.cpp hierarchy_node.cpp cylinder.cpp frustum.cpp
INCLUDES=gl_framework.hpp shader_util.hpp bike_model.hpp hierarchy_node.hpp cylinder.hpp frustum.hpp

all: $(BIN)

$(BIN): $(SRCS) $(INCLUDES)
	g++ $(CPPFLAGS) $(SRCS) -o $(BIN) $(LDFLAGS) $(LIBS)

clean:
	rm -f *~ *.o $(BIN)
